### ISSUE TITLE
Firefox console export

### ISSUE THREAD

**Issue by TomTheGeek** [jeffsikes/pandora_liked_songs_export#1]
The console on Firefox breaks up the output into individual objects so it's impossible to "copy object" on all of them at once. To get an export right click on the output array and selected "Store as Global Variable". That creates a var called 'temp0'. Then in the console run the following code to output the entire object as a string. This creates a new output that "copy object" can get all the data at once. 

`console.log(JSON.stringify(temp0, null, 2))`

**Comment by jeffsikes** [comment]
Thanks! Great idea. I've incorporated that into the script, and tested in Edge, Chrome and Firefox.
